correct values file stub for slack commandName
grafana/oncall pull request #1093
Opened 2023-01-05 21:22 UTC by thomasmitchell

# What this PR does

The templates actually generate the SLACK_SLASH_COMMAND_NAME envvar from `.Values.oncall.slack.commandName`, not `command`. This commit changes the default values file to reflect this.

## Which issue(s) this PR fixes

#1092 

## Checklist

- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated

^ Are these applicable with regards to updating the helm chart, not the core application? I did take the time to test both the default and changed value after this change in a kubernetes deployment.

2023-01-05 21:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/oncall?pullRequest=1093) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/oncall?pullRequest=1093) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/oncall?pullRequest=1093) it.</sub>

2023-01-11 11:57 UTC, joeyorlando requested changes
Hi there! 👋 
Thanks for the contribution. For the most part LGTM, just a few small things to address: Do you mind:
- updating the root `CHANGELOG.md`
- bumping the patch version in `helm/oncall/Chart.yaml`
- there seem to be a handful of references in `helm/oncall/README.md` to the old `command` attribute, can you update these?

2023-01-11 18:57 UTC, thomasmitchell commented
Made the requested changes, and rebased on top of now-current dev branch.

2023-01-12 06:44 UTC, joeyorlando commented on CHANGELOG.md
> +
```suggestion
- Helm chart: default values file and documentation now reflect the correct key to set for the Slack slash command name, `oncall.slack.commandName`.

```

2023-01-12 06:49 UTC, joeyorlando approved these changes

2023-01-12 07:03 UTC, merged