fix NPE in schedule user details
grafana/oncall pull request #1230
Opened 2023-01-26 13:45 UTC by maskin25

# What this PR does

Fix NPE 

## Which issue(s) this PR fixes

https://github.com/grafana/oncall/issues/1229

## Checklist

- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated

2023-01-26 14:59 UTC, teodosii requested changes

2023-01-26 14:59 UTC, teodosii commented on grafana-plugin/src/components/ScheduleUserDetails/ScheduleUserDetails.tsx
> +    : '';
Don't you like shorter hand?

```jsx
const slackWorkspaceName = teamStore.currentTeam.slack_team_identity?.cached_name?.replace(/[^0-9a-z]/gi, '') || ''
```

2023-01-27 13:54 UTC, maskin25 commented on grafana-plugin/src/components/ScheduleUserDetails/ScheduleUserDetails.tsx
> +    : '';
nice, fixed

2023-01-27 14:30 UTC, vadimkerr approved these changes

2023-01-27 14:40 UTC, merged