Add RBAC guidance to users and teams documentation
grafana/oncall pull request #1413
Opened 2023-02-24 18:30 UTC by alyssawada

# What this PR does
RBAC for OnCall will be GA with Grafana 9.4 release.
Update [this doc](https://grafana.com/docs/oncall/latest/configure-user-settings/) to include details about RBAC for OnCall and link to RBAC-specific docs.

## Which issue(s) this PR fixes
Issue #1399 

## Checklist

- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated

2023-02-24 18:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/oncall?pullRequest=1413) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/grafana/oncall?pullRequest=1413) before we can accept your contribution.<br/>**7** out of **8** committers have signed the CLA.<br/><br/>:white_check_mark: vadimkerr<br/>:white_check_mark: iskhakov<br/>:white_check_mark: mderynck<br/>:white_check_mark: joeyorlando<br/>:white_check_mark: alyssawada<br/>:white_check_mark: Konstantinov-Innokentii<br/>:white_check_mark: Ferril<br/>:x: actions-user<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/oncall?pullRequest=1413) it.</sub>

2023-03-06 09:51 UTC, joeyorlando commented
@alyssawada overall this LGTM. I think you have some extra commits in here causing the changes in the `/helm` directory. once that's sorted out I'll go ahead and approve (unless you meant to make those helm related changes?)

2023-03-09 01:35 UTC, iskhakov commented on helm/oncall/Chart.yaml
> +version: 1.1.29
I believe this change can be removed from this PR

2023-03-09 01:36 UTC, iskhakov requested changes
please remove the changes to the following files helm/oncall/Chart.lock, helm/oncall/Chart.lock, helm/oncall/Chart.lock

2023-03-13 09:09 UTC, joeyorlando commented
bump (cc: @alyssawada)

2023-03-14 06:08 UTC, joeyorlando approved these changes

2023-03-14 06:08 UTC, merged