Allow telegram DMs without channel connection
grafana/oncall pull request #142
Opened 2022-06-24 09:45 UTC by vadimkerr

2022-06-24 09:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/oncall?pullRequest=142) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/oncall?pullRequest=142) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/oncall?pullRequest=142) it.</sub>

2022-06-24 11:28 UTC, Konstantinov-Innokentii approved these changes

2022-06-25 09:23 UTC, Matvey-Kuk requested changes
Long-desired feature! Btw, I don't see if docs or instructions in the UI are updated. Aren't changes there also needed?

2022-06-27 09:50 UTC, vadimkerr commented
> Long-desired feature! Btw, I don't see if docs or instructions in the UI are updated. Aren't changes there also needed?

@Matvey-Kuk thanks! Added a line on usage without Telegram channel connection.

2022-06-27 15:06 UTC, Matvey-Kuk approved these changes

2022-06-28 08:11 UTC, merged