Allow changing team for escalation chains
grafana/oncall pull request #1658
Opened 2023-03-29 11:51 UTC by maskin25

# What this PR does

Allows changing team for escalation chains

## Which issue(s) this PR fixes

## Checklist

- [x] Unit, integration, and e2e (if applicable) tests updated
- [x] Documentation added (or `pr:no public docs` PR label added if not required)
- [x] `CHANGELOG.md` updated (or `pr:no changelog` PR label added if not required)

2023-03-29 15:56 UTC, vadimkerr commented on engine/apps/api/views/escalation_chain.py
> +            team = request.user.available_teams.get(public_primary_key=team_id)
Looks like this will break when copying an escalation chain without a team, right? I'd recommend adding a unit tests to check this scenario.

2023-03-29 17:22 UTC, vadimkerr commented on engine/apps/api/views/escalation_chain.py
> +            team = request.user.available_teams.get(public_primary_key=team_id)
Should be fixed in https://github.com/grafana/oncall/pull/1658/commits/0fedcd614bb662aa66a1eccfa478c88ef2687c89

2023-03-29 17:25 UTC, vadimkerr approved these changes

2023-03-29 18:05 UTC, Ukochka approved these changes

2023-03-30 05:50 UTC, teodosii commented on grafana-plugin/src/containers/EscalationChainForm/EscalationChainForm.tsx
> +    console.log(selectedTeam);
Please remove.

2023-03-30 05:50 UTC, teodosii commented on grafana-plugin/src/pages/escalation-chains/EscalationChains.tsx
> +console.log(config.bootData.user);
Here too

2023-03-30 06:18 UTC, teodosii requested changes
I've noticed a small bug here. When you create an escalation chain, the form is validated, when you set a copy the validation is no longer performed and you can have empty text escalation chains.

![image](https://user-images.githubusercontent.com/40542072/228746326-58b4c2a8-29e2-4122-a160-9332ca427c49.png)
![image](https://user-images.githubusercontent.com/40542072/228746363-0fdd2cbf-cdfb-4403-9120-ecb2e89b5fc5.png)

This only happens for copying, updating/creating do trigger the validation.

2023-03-30 09:33 UTC, vadimkerr commented
The empty name bug is fixed in https://github.com/grafana/oncall/pull/1658/commits/4f076ce6bd7dc90385da45d1540a048b75b79c4d. cc @teodosii

2023-03-30 09:43 UTC, merged