Webhooks 2 docs first draft
grafana/oncall pull request #1844
Opened 2023-04-27 22:48 UTC by mderynck

2023-06-15 13:32 UTC, Matvey-Kuk requested changes
Please update it according to recent docs restructure, for example webhooks now are not under "alert behavior"

2023-06-29 21:31 UTC, mderynck commented on docs/sources/outgoing-webhooks/integrate-jira/index.md
> +---
Do we want both incoming and outgoing for each integration to be a single page? Add the outgoing content to the existing page or keep the outgoing as separate pages?

2023-07-07 04:55 UTC, Matvey-Kuk commented on docs/sources/outgoing-webhooks/integrate-jira/index.md
> +---
I think single page would be noce

2023-07-12 14:49 UTC, Matvey-Kuk approved these changes

2023-07-13 20:39 UTC, merged