Helm zvonok env
grafana/oncall pull request #2563
Opened 2023-07-17 19:14 UTC by eugenefeel

# What this PR does
In this PR I added helm env for zvonok 
## Which issue(s) this PR fixes
When adding integration, they forgot to add zvonok settings to helm
#2520 
## Checklist

- [ ] Unit, integration, and e2e (if applicable) tests updated
- [ ] Documentation added (or `pr:no public docs` PR label added if not required)
- [ ] `CHANGELOG.md` updated (or `pr:no changelog` PR label added if not required)

2023-07-17 19:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/oncall?pullRequest=2563) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/grafana/oncall?pullRequest=2563) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: Evgeniy Mihaylovsky<br/>:x: eugenefeel<br/><hr/>**Evgeniy Mihaylovsky** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/oncall?pullRequest=2563) it.</sub>

2023-07-25 05:15 UTC, iskhakov commented
please consider adding tests for this case

2023-07-29 11:35 UTC, eugenefeel commented
> please consider adding tests for this case

Ok, I'll try but I never wrote tests for helm

2023-08-07 11:46 UTC, iskhakov requested changes
waiting for the tests

2023-12-25 01:46 UTC, closed without merging