181 add GitHub star
grafana/oncall pull request #386
Opened 2022-08-19 09:45 UTC by teodosii

PR for [1322](https://github.com/grafana/oncall-private/issues/1322)

Changes:
- Added `Star us on GitHub` for OSS

2022-08-23 11:16 UTC, maskin25 requested changes

2022-08-23 11:18 UTC, teodosii commented on grafana-plugin/src/components/NavBar/NavBarSubtitle.tsx
> +      <div className={cx('navbar-container')}>
Done

2022-08-23 11:55 UTC, maskin25 approved these changes

2022-09-01 08:49 UTC, maskin25 approved these changes

2022-09-02 12:41 UTC, merged