Update consts.ts
grafana/oncall pull request #4648
Opened 2024-07-10 08:39 UTC by iskhakov

# What this PR does

## Which issue(s) this PR closes

Closes [issue link here]

## Checklist

- [ ] Unit, integration, and e2e (if applicable) tests updated
- [ ] Documentation added (or `pr:no public docs` PR label added if not required)
- [ ] Added the relevant release notes label (see labels prefixed w/ `release:`). These labels dictate how your PR will
    show up in the autogenerated release notes.

2024-07-10 08:41 UTC, brojd approved these changes

2024-07-10 15:06 UTC, joeyorlando requested changes
I think this is proof that these shouldn't be hardcoded.. we discussed this a while back and decided to take the lower effort way out at the time.

My opinion would be to inject these env vars at build time, rather than having the app even need to know what prod/ops/dev is.

2024-07-10 15:57 UTC, joeyorlando reviewed
@mderynck also had some thoughts here. Instead of adding these consts at plugin build time, read them from a (new?) endpoint.

Maybe [this one](https://github.com/grafana/oncall/blob/dev/engine/apps/grafana_plugin/views/status.py#L76-L90)?

2024-07-12 08:58 UTC, iskhakov commented
@joeyorlando let's do this work within the new issue/pr scope. I need to merge this one as part of https://github.com/grafana/oncall-private/issues/2609

2024-07-24 13:47 UTC, joeyorlando approved these changes

2024-07-29 11:33 UTC, merged