472 wrong team
grafana/oncall pull request #520
Opened 2022-09-12 07:34 UTC by teodosii

-- [Work In Progress] --

Fix for #472

2022-09-20 09:00 UTC, vadimkerr approved these changes

2022-09-20 09:00 UTC, vadimkerr commented on engine/apps/api/views/user.py
> +        This method returns 403 and {"error_code": "wrong_team", "owner_team": {"name", "id", "email", "avatar_url"}}.
probably worth adding a comment why TeamFilteringMixin cannot be used here

2022-09-20 09:14 UTC, maskin25 commented
I don't like that you copypasted 

```
notFound?: boolean;
  wrongTeamError?: boolean;
  teamToSwitch?: { name: string; id: string };
  wrongTeamNoPermissions?: boolean;
```
to many pages, it would be good to wrap this state, requests, logic and so on into separate service/top level component and manage this stuff in one place to avoid copypaste

2022-09-20 09:15 UTC, maskin25 requested changes

2022-09-20 09:15 UTC, maskin25 commented on grafana-plugin/src/models/base_store.ts
> +    return await makeRequest(path, {
`params: { from_organization:fromOrganization? true: undefined}`

2022-09-20 09:15 UTC, maskin25 commented on grafana-plugin/src/models/schedule/schedule.ts
> +  async loadItem(id: Schedule['id'], skipErrorHandling = false): Promise<Schedule> {
great that you add typings for promises!

2022-09-26 08:04 UTC, maskin25 approved these changes

2022-09-29 11:59 UTC, merged