Fix dynamic label template validation
grafana/oncall pull request #5363
Opened 2024-12-13 04:58 UTC by Konstantinov-Innokentii

2024-12-13 05:33 UTC, Konstantinov-Innokentii commented on engine/apps/alerts/models/alert_receive_channel.py
> +    alert_group_labels_custom stores config of dynamic labels - mapping of incoming alert payload to labels
Just some renamigs & comments. Further refactoring needed.

2024-12-13 05:33 UTC, Konstantinov-Innokentii commented on engine/apps/labels/alert_group_labels.py
> -        key_id, value_id, template = label
Moved this to separate func

2024-12-13 05:33 UTC, Konstantinov-Innokentii commented on engine/apps/labels/alert_group_labels.py
> -        # check value length
Moved to validate_templated_value

2024-12-13 05:35 UTC, Konstantinov-Innokentii commented on engine/apps/labels/alert_group_labels.py
> +    label: "AlertReceiveChannel.DynamicLabelsEntryDB", keys, values, payload
it's old logic of applying custom labels, but without "static" values - they now live in integration associated labels exclusively. Also It calls _validate_templated_value to fix actual big with None values.

2024-12-17 16:59 UTC, joeyorlando approved these changes

2024-12-17 17:02 UTC, vadimkerr requested changes

2024-12-18 01:45 UTC, Konstantinov-Innokentii commented on engine/apps/alerts/models/alert_receive_channel.py
> +    alert_group_labels_custom: DynamicLabelsConfigDB = models.JSONField(null=True, default=None)
There is some further refactoring planned on that piece

2024-12-18 03:48 UTC, Konstantinov-Innokentii commented on engine/apps/api/serializers/alert_receive_channel.py
>          custom_labels: AlertGroupCustomLabelsAPI,
Yep, we should, it will be in separate PRs to keep bugfix tight.

2024-12-18 04:35 UTC, merged