fix: Fix postgresql engine initial migrations
grafana/oncall pull request #625
Opened 2022-10-07 08:20 UTC by sergeyshevch

Followup from #262. 
Migration 0005 will fail if the database engine is PostgreSQL. I faced such an issue in my initial migrations setup.

2022-10-07 08:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/oncall?pullRequest=625) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/oncall?pullRequest=625) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/oncall?pullRequest=625) it.</sub>

2022-10-07 08:21 UTC, sergeyshevch commented
@vadimkerr I guess you should look on it

2022-10-07 08:25 UTC, vadimkerr commented
Hey @sergeyshevch, thank you for the PR! I will take a look at it today.

2022-10-07 13:00 UTC, vadimkerr requested changes
I reproduced the issue you described, definetely a bug for setups using PostgreSQL as the database. The fix you prepared should generally solve the issue, but after applying the patch I'm getting the following error when running migrations:
```
django.db.utils.InternalError: current transaction is aborted, commands ignored until end of transaction block
```
Seems like we need to add `atomic = False` for this migration so these two operations in the migration are independent and catching `ProgrammingError` is enough. 

So I propose adding `atomic = False` as a class attribute for this particular `Migration`.

2022-10-07 13:00 UTC, vadimkerr commented on engine/apps/alerts/migrations/0005_alertgroup_cached_render_for_web.py
> +        except (OperationalError, ProgrammingError):
Could you please also add a comment, so it's clear that:
```
# duplicate coulumn error raises OperationalError for MySQL and SQLite, and ProgrammingError for PostgreSQL
```

2022-10-07 18:48 UTC, sergeyshevch commented
Ok. I will fix it on Monday

2022-10-18 13:05 UTC, vadimkerr commented
Closing this as already fixed by https://github.com/grafana/oncall/pull/660

2022-10-18 13:05 UTC, closed without merging